language: cpp
dist: trusty
sudo: required
matrix:
    include:
        -   os: linux
            env: COMPILER=g++-6 COMPILER_FLAGS="-Wall -Wpedantic -Wextra -Werror"
            addons:
                apt:
                    sources:
                        -   sourceline: "ppa:amarburg/opencv3"
                        -   ubuntu-toolchain-r-test
                    packages:
                        -   libopencv3
                        -   libopencv3-*-dev
                        -   g++-6
                        -   libboost1.55-all-dev
before_install:
    -   export CXX=${COMPILER}
    -   export CXXFLAGS=${COMPILER_FLAGS}
script:
    -   mkdir build
    -   cd build
    -   cmake .. -DCMAKE_BUILD_TYPE=Debug -DBOOST_LIBRARYDIR=/usr/lib/x86_64-linux-gnu
    -   cmake --build .
    -   ctest -VV
